# Base index 1 in windows and panes to avoid annoying pressing of 0
set -g base-index 1
setw -g pane-base-index 1

# vi keys for copy mode
set -g mode-keys vi
# use system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Use Vim keys to navigate panes (prefix + h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#>>>>> PLUGINS >>>>>>>>>>>>>>>>>>>>>>>>>>>>
# tmux packet manager, required to install/use plugins like this
set -g @plugin 'tmux-plugins/tpm'
# Keybinds and settings that should be acceptable for anyone 
set -g @plugin 'tmux-plugins/tmux-sensible'
# Save and restore your tmux session (prefix + C-s / prefix + C-r )
set -g @plugin 'tmux-plugins/tmux-resurrect'
# battery life
set -g @plugin 'tmux-plugins/tmux-battery'
# CPU usage
set -g @plugin 'tmux-plugins/tmux-cpu'
#Color theme
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

# # auto resurrect
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command}"
# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""
# memory usage
set -ag status-right "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse]󱀙  "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] #(awk '/MemTotal/ {t=$2} /MemAvailable/ {a=$2} END {printf \"%.0f%%\", (t-a)/t*100}' /proc/meminfo) "
set -agF status-right "#{E:@catppuccin_status_cpu}"
#set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
# date time
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] 󰃭 %a %d %b 󰥔 %H:%M "


# Disable automatic window names
set -g automatic-rename off

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.tmux/plugins/tpm/tpm

